export const theme = {
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
    xxxl: 48,
  },
  colors: {
    primary: '#5D71E2',
    primaryLight: '#8A97F3',
    primaryDark: '#4555C7',
    accent: '#F9AE42',
    background: '#F7F8FC',
    darkBackground: '#121A2E',
    cardBackground: '#FFFFFF',
    cardBackgroundDark: '#1E2746',
    white: '#FFFFFF',
    darkGray: '#555555',
    lightGray: '#E1E3EF',
    lightText: '#ffffff',
    text: '#333333',
    error: '#FF5252',
    success: '#4CAF50',
    gradient: ['#5D71E2', '#8A97F3'],
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    round: 25,
  },
  shadows: {
    small: {
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 2,
    },
    medium: {
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 5,
    },
    large: {
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 15,
      elevation: 8,
    },
  },
};
